import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import Blog from "./blog";

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
          h2 {
            font-size: 28px;
          }
          h3 {
            font-size: 20px;
          }
          h1 {
            font-size: 36px;
          }
        `}
      </style>
      <Head>
        <title>Hunting Blogger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Hunting Blogger</h1>
        <br />
        {/* SSR */}
        <Image
          className={styles.myimg}
          src="/homeimg.jpg"
          width={240}
          height={160}
        ></Image>
        {/* SSG
        <img src="/homeimg.jpg" width={240} height={160} alt="nextPOC" /> */}
        {/* <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div> */}
        <div className={styles.blogs}>
          <h2>Popular Blogs</h2>
          <div className={styles.blogItem}>
            <h3>How to learn JavaScript in 2022</h3>
            <p>hello javascript</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn JavaScript in 2022</h3>
            <p>hello javascript</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn JavaScript in 2022</h3>
            <p>hello javascript</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn JavaScript in 2022</h3>
            <p>hello javascript</p>
          </div>
        </div>
      </main>
    </div>
  );
}
